### ISSUE TITLE
Not draggable on mobile

### ISSUE THREAD

**Issue by qriley** [tzinas/react-percentages-slider#3]
Cannot adjust the sections on mobile. Will look into this

**Comment by qriley** [comment]
document.addEventListener('mousemove', handleMouseMove)
On touch equivalent 

    document.addEventListener('touchmove', handleMouseMove)
Similarly

    document.addEventListener('mouseup', handleMouseUp)
On touch equivalent 

    document.addEventListener('touchend', handleMouseUp)

**Comment by tzinas** [comment]
Feel free to create a pull request including the above changes. I can also look into this in the next couple of days.

**Comment by qriley** [comment]
Fixed on PR #4 
Can close issue on merge
